version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build (all)
          command: make test
      - store_artifacts:
          path: _dist/
          destination: bin
